#
# WARNING: To install Immich, follow our guide: https://docs.immich.app/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

# This compose file is only invoked for `make dev-scale`

name: immich-dev

services:
  immich-server:
    extends:
      file: docker-compose.dev.yml
      service: immich-server

    container_name: !reset []
    ports: !reset
      - 9228-9230:9230
      - 9231-9233:9231
      - 2283-2285:2283

  immich-web:
    extends:
      file: docker-compose.dev.yml
      service: immich-web

  immich-machine-learning:
    extends:
      file: docker-compose.dev.yml
      service: immich-machine-learning

  redis:
    extends:
      file: docker-compose.dev.yml
      service: redis

  database:
    extends:
      file: docker-compose.dev.yml
      service: database

volumes:
  model-cache:
  prometheus-data:
  grafana-data:
  pnpm-store:
  server-node_modules:
  web-node_modules:
  github-node_modules:
  cli-node_modules:
  docs-node_modules:
  e2e-node_modules:
  sdk-node_modules:
  app-node_modules:
  sveltekit:
  coverage:
